# FAKE REVIEW NODE EMBEDDING

In [4]:
!pip install torch-scatter torch-sparse torch-cluster torch-spline-conv torch-geometric -f https://data.pyg.org/whl/torch-1.12.0+cpu.html

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://data.pyg.org/whl/torch-1.12.0+cpu.html
     |████████████████████████████████| 286 kB 256 kB/s 
     |████████████████████████████████| 641 kB 53.7 MB/s 
     |████████████████████████████████| 311 kB 275 kB/s 
     |████████████████████████████████| 121 kB 284 kB/s 
     |████████████████████████████████| 467 kB 38.9 MB/s 
  Created wheel for torch-geometric: filename=torch_geometric-2.1.0.post1-py3-none-any.whl size=689859 sha256=1d5972be7cbe79f247156e118ac0146cb19d24f376bf3e180c66391651a93a2c
  Stored in directory: /root/.cache/pip/wheels/d1/cb/43/f7f2e472de4d7cff31bceddadc36d634e1e545fbc17961c282
Successfully built torch-geometric


In [148]:
# importing all necessary libraries
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string
import os
import networkx as nx
#import stellargraph as sg
#from stellargraph import StellarGraph
from sklearn import preprocessing, model_selection
from IPython.display import display, HTML
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
#from node2vec import Node2Vec as n2v
sns.set()
from sklearn.preprocessing import StandardScaler
%matplotlib inline

In [149]:
# importing all necessary libraries
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import string
import os
import networkx as nx
from sklearn import preprocessing, model_selection
from IPython.display import display, HTML
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
#from node2vec import Node2Vec as n2v
sns.set()

%matplotlib inline

In [150]:
import os, sys
from copy import deepcopy
import numpy as np
import pandas as pd

import torch as th
import torch.nn as nn
from torch import optim
import torch.nn.functional as F

import matplotlib.pyplot as plt
%matplotlib inline

In [151]:
#importing libraries
import numpy as np
import pandas as pd
import nltk
import matplotlib.pyplot as plt
import statistics
import math
import os
from sklearn.model_selection import KFold, StratifiedKFold, cross_val_score
from sklearn.metrics import confusion_matrix
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
nltk.download('omw-1.4')
#nltk.download('all')
import re
pd.set_option('max_colwidth', 800)


#importing Libraies
import networkx as nx
import matplotlib.pyplot as plt
from numpy import genfromtxt
import collections
from collections import OrderedDict

import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.feature_selection import SelectFromModel
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.linear_model import LinearRegression,LogisticRegression, RidgeClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report,accuracy_score

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [152]:
import os
import torch
os.environ['TORCH'] = torch.__version__
print(torch.__version__)

1.12.1+cu113


In [153]:
%matplotlib inline
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE

In [154]:
#loading dataset
df=pd.read_csv('/content/deceptive.csv')
df.head()

deceptive   hotel  polarity       source  \
0  truthful  conrad  positive  TripAdvisor   
1  truthful   hyatt  positive  TripAdvisor   
2  truthful   hyatt  positive  TripAdvisor   
3  truthful    omni  positive  TripAdvisor   
4  truthful   hyatt  positive  TripAdvisor   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text  \
0                                                                                                                                                                                                                                    We stayed for a one night getaway with family on a thursday. Triple AAA rate of 173 was a steal. 7th floor room complete with 44in plasma TV bose stereo, voss and evian water, and gorgeous bathroom(no tub but was fine for us) Concierge was very helpful. You cannot beat this location... Only flaw was breakfast was pricey and service was very very slow(2hours for four kids and four adults on a friday morning) even though there were only two other tables in the restaurant. Food was very good so it was worth the wait. I would return in a heartbeat. A gem in chicago... \n   
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Triple A rate with upgrade to view room was less than $200 which also included breakfast vouchers. Had a great view of river, lake, Wrigley Bldg. & Tribune Bldg. Most major restaurants, Shopping, Sightseeing attractions within walking distance. Large room with a very comfortable bed. \n   
2  This comes a little late as I'm finally catching up on my reviews from the past several months:) A dear friend and I stayed at the Hyatt Regency in late October 2007 for one night while visiting a friend and her husband from out of town. This hotel is perfect, IMO. Easy check in and check out. Lovely, clean, comfortable rooms with great views of the city. I know this area pretty well and it's very convenient to many downtown Chicago attractions. We had dinner and went clubing with our friends around Division St.. We had no problems getting cabs back and forth to the Hyatt and there's even public transportation right near by but we didn't bother since we only needed cabs from and to the hotel. Parking, as is usual for Chicago, was expensive but we were able to get our car out quickly (h...   
3                                                                                             The Omni Chicago really delivers on all fronts, from the spaciousness of the rooms to the helpful staff to the prized location on Michigan Avenue. While this address in Chicago requires a high level of quality, the Omni delivers. Check in for myself and a whole group of people with me was under 3 minutes, the staff had plentiful recommendations for dining and events, and the rooms are some of the largest

In [155]:
df.shape

(1600, 6)

In [156]:
#df.drop_duplicates(inplace=True)

In [157]:
df['Class'].value_counts()

1    800
0    800
Name: Class, dtype: int64

In [158]:
# dropping unnecessary columns. 
df.drop(['deceptive', 'hotel', 'polarity', 'source'], axis = 1, inplace=True)
df.head()

text  \
0                                                                                                                                                                                                                                    We stayed for a one night getaway with family on a thursday. Triple AAA rate of 173 was a steal. 7th floor room complete with 44in plasma TV bose stereo, voss and evian water, and gorgeous bathroom(no tub but was fine for us) Concierge was very helpful. You cannot beat this location... Only flaw was breakfast was pricey and service was very very slow(2hours for four kids and four adults on a friday morning) even though there were only two other tables in the restaurant. Food was very good so it was worth the wait. I would return in a heartbeat. A gem in chicago... \n   
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Triple A rate with upgrade to view room was less than $200 which also included breakfast vouchers. Had a great view of river, lake, Wrigley Bldg. & Tribune Bldg. Most major restaurants, Shopping, Sightseeing attractions within walking distance. Large room with a very comfortable bed. \n   
2  This comes a little late as I'm finally catching up on my reviews from the past several months:) A dear friend and I stayed at the Hyatt Regency in late October 2007 for one night while visiting a friend and her husband from out of town. This hotel is perfect, IMO. Easy check in and check out. Lovely, clean, comfortable rooms with great views of the city. I know this area pretty well and it's very convenient to many downtown Chicago attractions. We had dinner and went clubing with our friends around Division St.. We had no problems getting cabs back and forth to the Hyatt and there's even public transportation right near by but we didn't bother since we only needed cabs from and to the hotel. Parking, as is usual for Chicago, was expensive but we were able to get our car out quickly (h...   
3                                                                                             The Omni Chicago really delivers on all fronts, from the spaciousness of the rooms to the helpful staff to the prized location on Michigan Avenue. While this address in Chicago requires a high level of quality, the Omni delivers. Check in for myself and a whole group of people with me was under 3 minutes, the staff had plentiful recommendations for dining and events, and the rooms are some of the largest you'll find at this price range in Chicago. Even the 'standard' room has a separate living area and work desk. The fitness center has free weights, weight machines, and two rows of cardio equipment. I shared the room with 7 others and did not feel cramped in any way! All in all, a great property! \n   
4                                                                                                                                                                                                                                                                                                                                                                                                                                I asked for a high floor away from the elevator and that is what I got. The room was pleasantly decorated, functional and very clean. I didn't need a whole lot of service but when I did they were pleasant and prompt. I used the fitness center which was well equipped and everything was in working order. It is in a great location at one end of the Mic

In [159]:
# Cleaning Raw tweets
def clean_text(text):
    
    #remove emails
    text = ' '.join([i for i in text.split() if '@' not in i])
    
    #remove web address
    text = re.sub('http[s]?://\S+', '', text)

    #remove brackets and parantheses (and removing the text inside the brackets and parantheses)
    text = re.sub("[\(\[].*?[\)\]]", "", text)

    #remove punctuations
    text = re.sub(r'[^\w\s]', ' ', text)
    
    #Filter to allow only alphabets and numbers
    text = re.sub(r'[^a-zA-Z\']', ' ', text)
    
    #Remove Unicode characters
    text = re.sub(r'[^\x00-\x7F]+', '', text)

    #remove double spaces 
    text = re.sub('\s+', ' ', text)
    
    return text

In [160]:
# applying that into function.
df["clean_text"] = df['text'].apply(lambda x: clean_text(x))
df.head(10)

text  \
0                                                                                                                                                                                                                                    We stayed for a one night getaway with family on a thursday. Triple AAA rate of 173 was a steal. 7th floor room complete with 44in plasma TV bose stereo, voss and evian water, and gorgeous bathroom(no tub but was fine for us) Concierge was very helpful. You cannot beat this location... Only flaw was breakfast was pricey and service was very very slow(2hours for four kids and four adults on a friday morning) even though there were only two other tables in the restaurant. Food was very good so it was worth the wait. I would return in a heartbeat. A gem in chicago... \n   
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Triple A rate with upgrade to view room was less than $200 which also included breakfast vouchers. Had a great view of river, lake, Wrigley Bldg. & Tribune Bldg. Most major restaurants, Shopping, Sightseeing attractions within walking distance. Large room with a very comfortable bed. \n   
2  This comes a little late as I'm finally catching up on my reviews from the past several months:) A dear friend and I stayed at the Hyatt Regency in late October 2007 for one night while visiting a friend and her husband from out of town. This hotel is perfect, IMO. Easy check in and check out. Lovely, clean, comfortable rooms with great views of the city. I know this area pretty well and it's very convenient to many downtown Chicago attractions. We had dinner and went clubing with our friends around Division St.. We had no problems getting cabs back and forth to the Hyatt and there's even public transportation right near by but we didn't bother since we only needed cabs from and to the hotel. Parking, as is usual for Chicago, was expensive but we were able to get our car out quickly (h...   
3                                                                                             The Omni Chicago really delivers on all fronts, from the spaciousness of the rooms to the helpful staff to the prized location on Michigan Avenue. While this address in Chicago requires a high level of quality, the Omni delivers. Check in for myself and a whole group of people with me was under 3 minutes, the staff had plentiful recommendations for dining and events, and the rooms are some of the largest you'll find at this price range in Chicago. Even the 'standard' room has a separate living area and work desk. The fitness center has free weights, weight machines, and two rows of cardio equipment. I shared the room with 7 others and did not feel cramped in any way! All in all, a great property! \n   
4                                                                                                                                                                                                                                                                                                                                                                                                                                I asked for a high floor away from the elevator and that is what I got. The room was pleasantly decorated, functional and very clean. I didn't need a whole lot of service but when I did they were pleasant and prompt. I used the fitness center which was well equipped and everything was in working order. It is in a great location at one end of the Mic

In [161]:
# dropping the uncleaned text column "text"
df = df.drop(['text'], axis=1)

In [162]:
# renaming the column
df.rename(columns = {'clean_text':'text'}, inplace = True)
df.head()

Class  \
0      1   
1      1   
2      1   
3      1   
4      1   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              text  
0                                                                                                                                                                                                                                                                                                                                                 We stayed for a one night getaway with family on a thursday Triple AAA rate of was a steal th floor room complete with in plasma TV bose stereo voss and evian water and gorgeous bathroom Concierge was very helpful You cannot beat this location Only flaw was breakfast was pricey and service was very very slow even though there were only two other tables in the restaurant Food was very good so it was worth the wait I would return in a heartbeat A gem in chicago   
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Triple A rate with upgrade to view room was less than which also included breakfast vouchers Had a great view of river lake Wrigley Bldg Tribune Bldg Most major restaurants Shopping Sightseeing attractions within walking distance Large room with a very comfortable bed   
2  This comes a little late as I m finally catching up on my reviews from the past several months A dear friend and I stayed at the Hyatt Regency in late October for one night while visiting a friend and her husband from out of town This hotel is perfect IMO Easy check in and check out Lovely clean comfortable rooms with great views of the city I know this area pretty well and it s very convenient to many downtown Chicago attractions We had dinner and went clubing with our friends around Division St We had no problems getting cabs back and forth to the Hyatt and there s even public transportation right near by but we didn t bother since we only needed cabs from and to the hotel Parking as is usual for Chicago was expensive but we were able to get our car out quickly No problems at all and...  
3                                                                                                                   The Omni Chicago really delivers on all fronts from the spaciousness of the rooms to the helpful staff to the prized location on Michigan Avenue While this address in Chicago requires a high level of quality the Omni delivers Check in for myself and a whole group of people with me was under minutes the staff had plentiful recommendations for dining and events and the rooms are some of the largest you ll find at this price range in Chicago Even the standard room has a separate living area and work desk The fitness center has free weights weight machines and two rows of cardio equipment I 

In [163]:
import spacy
#loading the english language small model of spacy
en = spacy.load('en_core_web_sm')
sw_spacy = en.Defaults.stop_words
print(sw_spacy)

{'or', 'last', 'i', 'only', 'may', 'has', 'both', 'themselves', 'whereafter', 'therein', 'of', 'part', 'am', 'hereby', 'whither', 'often', 'together', 'empty', 'doing', 'meanwhile', 'sixty', 'if', 'two', 'at', 'off', 'sometimes', 'each', 'for', 'beforehand', 'becoming', 'they', 'every', 'be', 'ten', 'than', 'next', 'call', 'it', 'except', 'side', 'once', 'thus', "'m", 'fifteen', 'always', 'an', 'itself', "n't", 'yourself', 'anywhere', 'anything', 'can', '’re', 'four', 'to', 'hers', 'many', 'somewhere', 'down', 'why', 'never', 'on', 'hereafter', 'formerly', 'that', 'into', 'up', 'with', 'several', 'onto', 'your', 'do', 'herein', 'was', 'we', 'former', 'because', 'own', 'under', 'go', 'again', 'while', 'whom', 'whenever', 'less', 'any', 'really', 'sometime', 'about', 'thru', 'from', 'much', 'his', 'namely', 'ca', 'show', 'nine', 'alone', 'through', 'take', 'full', 'put', 'which', 'who', 'whereupon', 'will', 'something', 'front', 'becomes', 'anyway', 'himself', 'our', 'whoever', 'none', '

In [164]:
import nltk
from nltk.corpus import stopwords
sw_nltk = stopwords.words('english')
print(sw_nltk)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [165]:
sw_nltk.extend(['th','stay'])
print(len(sw_nltk))

181


In [166]:
# preprocessing the data (removing stopwords, convert the sentence to lower case, and also applying lemmatization to get meaningful words )
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer
#stop_words = set(stopwords.words('english'))
ps=PorterStemmer()
wnl=WordNetLemmatizer()
def clean_lemma(review):
    review = review.lower()
    review = review.split()
    review = [wnl.lemmatize(word) for word in review if word not in sw_nltk]
    review = [wnl.lemmatize(word) for word in review if word not in sw_spacy]
    review = ' '.join(review)
    return review

In [167]:
# using lemmatization
df['text']=df['text'].apply(clean_lemma)
df.head()

Class  \
0      1   
1      1   
2      1   
3      1   
4      1   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      text  
0                                                                                                                                                                                                                                                            stayed night getaway family thursday triple aaa rate steal floor room complete plasma tv bose stereo voss evian water gorgeous bathroom concierge helpful beat location flaw breakfast pricey service slow table restaurant food good worth wait return heartbeat gem chicago  
1                                                                                                                                                                                                                                                                                                                                 triple rate upgrade view room le included breakfast voucher great view river lake wrigley bldg tribune bldg major restaurant shopping sightseeing attraction walking distance large room comfortable bed  
2  come little late finally catching review past month dear friend stayed hyatt regency late october night visiting friend husband town hotel perfect imo easy check check lovely clean comfortable room great view city know area pretty convenient downtown chicago attraction dinner went clubing friend division st problem getting cab forth hyatt public transportation right near bother needed cab hotel parking usual chicago expensive able car quickly problem best got rate hotwire downright steal area chicago quality hotel  
3                                                                                                                      omni chicago delivers spaciousness room helpful staff prized location michigan avenue address chicago requires high level quality omni delivers check group people minute staff plentiful recommendation dining event room largest find price range chicago standard room separate living area work desk fitness center free weight weight machine row cardio equipment shared room feel cramped way great property  
4                                                                                                                                                                                                                                                                                                                                asked high floor away elevator got room pleasantly decorated functional clean need lot service pleasant prompt fitness center equipped working order great location end michigan avenue shopping district

### FEATURE EXTRACTION

In [168]:
x = df['text']
y = df['Class']

In [169]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer 
from sklearn.feature_extraction.text import TfidfVectorizer
cv=TfidfVectorizer()
corpii=cv.fit_transform(x) 

In [170]:
feature_names = cv.get_feature_names()
#feature_names

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [171]:
len(feature_names)

7905

In [172]:
u1 = pd.DataFrame(corpii.toarray(), columns=feature_names)
u1.head()

aaa  aaahed  aback  abassador  abd  ability      able  abound  abrupt  \
0  0.217034     0.0    0.0        0.0  0.0      0.0  0.000000     0.0     0.0   
1  0.000000     0.0    0.0        0.0  0.0      0.0  0.000000     0.0     0.0   
2  0.000000     0.0    0.0        0.0  0.0      0.0  0.090437     0.0     0.0   
3  0.000000     0.0    0.0        0.0  0.0      0.0  0.000000     0.0     0.0   
4  0.000000     0.0    0.0        0.0  0.0      0.0  0.000000     0.0     0.0   

   abruptly  ...  yucky  yummo  yummy  yunan  yup  zagat  zest  zipped  zone  \
0       0.0  ...    0.0    0.0    0.0    0.0  0.0    0.0   0.0     0.0   0.0   
1       0.0  ...    0.0    0.0    0.0    0.0  0.0    0.0   0.0     0.0   0.0   
2       0.0  ...    0.0    0.0    0.0    0.0  0.0    0.0   0.0     0.0   0.0   
3       0.0  ...    0.0    0.0    0.0    0.0  0.0    0.0   0.0     0.0   0.0   
4       0.0  ...    0.0    0.0    0.0    0.0  0.0    0.0   0.0     0.0   0.0   

   zoo  
0  0.0  
1  0.0  
2  0.0  
3  0.0  
4  0.0  

[5 rows x 7905 columns]

### FEATURE SELECTION

In [173]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
# Two features with highest chi-squared statistics are selected
chi2_features = SelectKBest(chi2, k = 1000)
X_kbest_features = chi2_features.fit_transform(u1, y)

In [174]:
chi_support = chi2_features.get_support()

In [175]:
chi_feature = u1.loc[:,chi_support].columns.tolist()

In [176]:
chi_feature

['accept',
 'accepted',
 'accomidations',
 'accommodated',
 'accommodation',
 'accomodations',
 'according',
 'accurate',
 'acknowledged',
 'acted',
 'adding',
 'address',
 'adult',
 'advantage',
 'advertises',
 'advisor',
 'affair',
 'affinia',
 'affordability',
 'agent',
 'al',
 'alive',
 'allegro',
 'allergenic',
 'allergy',
 'alley',
 'allowed',
 'amazing',
 'ambassador',
 'amenity',
 'angie',
 'angry',
 'anniversary',
 'annoying',
 'anthony',
 'anybody',
 'appointed',
 'april',
 'architectes',
 'arranging',
 'ask',
 'asleep',
 'associate',
 'assuming',
 'atmosphere',
 'attached',
 'attack',
 'attempted',
 'attended',
 'attending',
 'attraction',
 'attractive',
 'aug',
 'authorization',
 'av',
 'available',
 'ave',
 'aveda',
 'avenue',
 'award',
 'aware',
 'awful',
 'bacon',
 'badly',
 'baggage',
 'bakery',
 'ball',
 'bar',
 'bare',
 'bargain',
 'barking',
 'based',
 'basement',
 'basil',
 'bath',
 'bathroom',
 'battery',
 'beautiful',
 'beautifull',
 'beautifully',
 'beauty',
 'be

In [177]:
X_kbest_features

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [178]:
u3 = pd.DataFrame(X_kbest_features, columns = chi_feature)
u3.head()

accept  accepted  accomidations  accommodated  accommodation  \
0     0.0       0.0            0.0           0.0            0.0   
1     0.0       0.0            0.0           0.0            0.0   
2     0.0       0.0            0.0           0.0            0.0   
3     0.0       0.0            0.0           0.0            0.0   
4     0.0       0.0            0.0           0.0            0.0   

   accomodations  according  accurate  acknowledged  acted  ...  wouldnt  \
0            0.0        0.0       0.0           0.0    0.0  ...      0.0   
1            0.0        0.0       0.0           0.0    0.0  ...      0.0   
2            0.0        0.0       0.0           0.0    0.0  ...      0.0   
3            0.0        0.0       0.0           0.0    0.0  ...      0.0   
4            0.0        0.0       0.0           0.0    0.0  ...      0.0   

    wrigley  wrong  wrote  year  yellow  yes  young  yummy  zone  
0  0.000000    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  
1  0.247551    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  
2  0.000000    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  
3  0.000000    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  
4  0.000000    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  

[5 rows x 1000 columns]

### Creating PYG graph

In [179]:
X1 = pd.concat([u3, df['Class']], axis=1)
X1.head()

accept  accepted  accomidations  accommodated  accommodation  \
0     0.0       0.0            0.0           0.0            0.0   
1     0.0       0.0            0.0           0.0            0.0   
2     0.0       0.0            0.0           0.0            0.0   
3     0.0       0.0            0.0           0.0            0.0   
4     0.0       0.0            0.0           0.0            0.0   

   accomodations  according  accurate  acknowledged  acted  ...   wrigley  \
0            0.0        0.0       0.0           0.0    0.0  ...  0.000000   
1            0.0        0.0       0.0           0.0    0.0  ...  0.247551   
2            0.0        0.0       0.0           0.0    0.0  ...  0.000000   
3            0.0        0.0       0.0           0.0    0.0  ...  0.000000   
4            0.0        0.0       0.0           0.0    0.0  ...  0.000000   

   wrong  wrote  year  yellow  yes  young  yummy  zone  Class  
0    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0      1  
1    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0      1  
2    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0      1  
3    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0      1  
4    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0      1  

[5 rows x 1001 columns]

In [180]:
mainDataDFWoClass=X1.copy()
mainDataDFWoClass.drop(columns=['Class'],inplace=True)
mainDataDFWoClass

accept  accepted  accomidations  accommodated  accommodation  \
0        0.0       0.0            0.0           0.0       0.000000   
1        0.0       0.0            0.0           0.0       0.000000   
2        0.0       0.0            0.0           0.0       0.000000   
3        0.0       0.0            0.0           0.0       0.000000   
4        0.0       0.0            0.0           0.0       0.000000   
...      ...       ...            ...           ...            ...   
1595     0.0       0.0            0.0           0.0       0.000000   
1596     0.0       0.0            0.0           0.0       0.000000   
1597     0.0       0.0            0.0           0.0       0.121806   
1598     0.0       0.0            0.0           0.0       0.000000   
1599     0.0       0.0            0.0           0.0       0.000000   

      accomodations  according  accurate  acknowledged  acted  ...  wouldnt  \
0               0.0        0.0       0.0           0.0    0.0  ...      0.0   
1               0.0        0.0       0.0           0.0    0.0  ...      0.0   
2               0.0        0.0       0.0           0.0    0.0  ...      0.0   
3               0.0        0.0       0.0           0.0    0.0  ...      0.0   
4               0.0        0.0       0.0           0.0    0.0  ...      0.0   
...             ...        ...       ...           ...    ...  ...      ...   
1595            0.0        0.0       0.0           0.0    0.0  ...      0.0   
1596            0.0        0.0       0.0           0.0    0.0  ...      0.0   
1597            0.0        0.0       0.0           0.0    0.0  ...      0.0   
1598            0.0        0.0       0.0           0.0    0.0  ...      0.0   
1599            0.0        0.0       0.0           0.0    0.0  ...      0.0   

       wrigley  wrong  wrote  year  yellow  yes  young  yummy  zone  
0     0.000000    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  
1     0.247551    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  
2     0.000000    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  
3     0.000000    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  
4     0.000000    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  
...        ...    ...    ...   ...     ...  ...    ...    ...   ...  
1595  0.000000    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  
1596  0.000000    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  
1597  0.000000    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  
1598  0.000000    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  
1599  0.000000    0.0    0.0   0.0     0.0  0.0    0.0    0.0   0.0  

[1600 rows x 1000 columns]

In [181]:
classList=list(df['Class'])

In [182]:
def self_cosine_vectorized(a):
    dots = a.dot(a.T)
    sqrt_sums = np.sqrt((a**2).sum(1))
    cosine_dists = 1 - (dots/sqrt_sums)/sqrt_sums[:,None]
    np.fill_diagonal(cosine_dists,0)
    return cosine_dists

In [183]:
dist = self_cosine_vectorized(mainDataDFWoClass.values) 
dist

array([[0.        , 0.9405905 , 0.84884211, ..., 0.9611148 , 0.94566963,
        0.91649604],
       [0.9405905 , 0.        , 0.93565398, ..., 1.        , 1.        ,
        0.98463312],
       [0.84884211, 0.93565398, 0.        , ..., 0.89014397, 0.95655559,
        0.89588661],
       ...,
       [0.9611148 , 1.        , 0.89014397, ..., 0.        , 0.97014172,
        0.94950192],
       [0.94566963, 1.        , 0.95655559, ..., 0.97014172, 0.        ,
        0.98234986],
       [0.91649604, 0.98463312, 0.89588661, ..., 0.94950192, 0.98234986,
        0.        ]])

In [184]:
# Converting array into dataframe format
X1 = pd.DataFrame(dist)
X1.head(10)

0         1         2         3         4         5         6     \
0  0.000000  0.940591  0.848842  0.928784  0.886990  0.896077  0.839965   
1  0.940591  0.000000  0.935654  0.989527  0.980619  0.980874  0.908291   
2  0.848842  0.935654  0.000000  0.947094  0.983019  0.909841  0.980025   
3  0.928784  0.989527  0.947094  0.000000  0.684181  0.958003  0.940565   
4  0.886990  0.980619  0.983019  0.684181  0.000000  0.936677  0.912331   
5  0.896077  0.980874  0.909841  0.958003  0.936677  0.000000  0.911778   
6  0.839965  0.908291  0.980025  0.940565  0.912331  0.911778  0.000000   
7  0.844270  0.952800  0.947310  0.872738  0.932780  0.875309  0.956746   
8  0.923193  0.954079  0.956790  0.971759  0.894696  0.918146  0.981739   
9  0.946345  0.815788  0.881688  0.920519  0.911928  0.941594  0.966583   

       7         8         9     ...      1590      1591      1592      1593  \
0  0.844270  0.923193  0.946345  ...  0.923215  0.904583  0.962440  0.920801   
1  0.952800  0.954079  0.815788  ...  0.904359  0.960733  1.000000  1.000000   
2  0.947310  0.956790  0.881688  ...  0.838218  0.984251  0.952820  0.953599   
3  0.872738  0.971759  0.920519  ...  0.960120  0.986052  1.000000  1.000000   
4  0.932780  0.894696  0.911928  ...  1.000000  0.965750  0.984397  1.000000   
5  0.875309  0.918146  0.941594  ...  0.924814  0.988404  0.977021  0.968314   
6  0.956746  0.981739  0.966583  ...  0.926888  0.931652  0.962386  0.973458   
7  0.000000  0.811167  0.907327  ...  0.815698  0.902117  0.968446  1.000000   
8  0.811167  0.000000  0.962480  ...  0.944162  0.927032  0.986188  0.970462   
9  0.907327  0.962480  0.000000  ...  0.869490  0.990616  0.995631  1.000000   

       1594      1595      1596      1597      1598      1599  
0  0.904900  0.982124  1.000000  0.961115  0.945670  0.916496  
1  0.986527  0.987614  1.000000  1.000000  1.000000  0.984633  
2  0.964032  0.934771  0.958112  0.890144  0.956556  0.895887  
3  0.976680  0.936685  0.966877  0.941250  1.000000  0.986701  
4  1.000000  0.971950  1.000000  0.975788  1.000000  0.954159  
5  0.968323  0.932283  0.969240  0.919454  0.975326  0.902761  
6  0.986274  0.917446  0.982822  0.959163  0.986221  0.925638  
7  0.881500  0.861830  0.964422  0.875662  0.991950  0.954912  
8  0.878265  0.950494  0.957150  0.944069  0.961946  0.925325  
9  0.950912  0.955730  0.948196  0.920543  0.966585  0.987046  

[10 rows x 1600 columns]

In [185]:
# taking average
y = np.average(X1)
y

0.9302306946195295

In [186]:
adjmat_df=X1.copy()

In [187]:
adjmat_df[adjmat_df < y]=0
adjmat_df[adjmat_df >= y]=1

In [188]:
adjmat_df

0     1     2     3     4     5     6     7     8     9     ...  1590  \
0      0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   1.0  ...   0.0   
1      1.0   0.0   1.0   1.0   1.0   1.0   0.0   1.0   1.0   0.0  ...   0.0   
2      0.0   1.0   0.0   1.0   1.0   0.0   1.0   1.0   1.0   0.0  ...   0.0   
3      0.0   1.0   1.0   0.0   0.0   1.0   1.0   0.0   1.0   0.0  ...   1.0   
4      0.0   1.0   1.0   0.0   0.0   1.0   0.0   1.0   0.0   0.0  ...   1.0   
...    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
1595   1.0   1.0   1.0   1.0   1.0   1.0   0.0   0.0   1.0   1.0  ...   0.0   
1596   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   0.0   
1597   1.0   1.0   0.0   1.0   1.0   0.0   1.0   0.0   1.0   0.0  ...   0.0   
1598   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   1.0   
1599   0.0   1.0   0.0   1.0   1.0   0.0   0.0   1.0   0.0   1.0  ...   0.0   

      1591  1592  1593  1594  1595  1596  1597  1598  1599  
0      0.0   1.0   0.0   0.0   1.0   1.0   1.0   1.0   0.0  
1      1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
2      1.0   1.0   1.0   1.0   1.0   1.0   0.0   1.0   0.0  
3      1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
4      1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  
...    ...   ...   ...   ...   ...   ...   ...   ...   ...  
1595   1.0   1.0   1.0   1.0   0.0   1.0   1.0   1.0   1.0  
1596   0.0   1.0   1.0   1.0   1.0   0.0   0.0   0.0   0.0  
1597   1.0   1.0   1.0   1.0   1.0   0.0   0.0   1.0   1.0  
1598   1.0   1.0   0.0   1.0   1.0   0.0   1.0   0.0   1.0  
1599   0.0   0.0   1.0   0.0   1.0   0.0   1.0   1.0   0.0  

[1600 rows x 1600 columns]

In [189]:
adjmat_df.index =adjmat_df.columns

In [190]:
# Create networkx graph object
G = nx.from_pandas_adjacency(adjmat_df,create_using = nx.Graph())
print(nx.info(G))

Graph with 1600 nodes and 758282 edges


In [191]:
labels = np.asarray(df['Class']).astype(np.int64)
labels

array([1, 1, 1, ..., 0, 0, 0])

In [192]:
adj = nx.to_scipy_sparse_matrix(G).tocoo()
adj

<1600x1600 sparse matrix of type '<class 'numpy.float64'>'
	with 1516564 stored elements in COOrdinate format>

In [193]:
row = torch.from_numpy(adj.row.astype(np.int64)).to(torch.long)
row

tensor([   0,    0,    0,  ..., 1599, 1599, 1599])

In [194]:
col = torch.from_numpy(adj.col.astype(np.int64)).to(torch.long)
col

tensor([   1,    9,   13,  ..., 1595, 1597, 1598])

In [195]:
edge_index = torch.stack([row, col], dim=0)
edge_index

tensor([[   0,    0,    0,  ..., 1599, 1599, 1599],
        [   1,    9,   13,  ..., 1595, 1597, 1598]])

In [196]:
# using degree as embedding
embeddings = np.array(list(dict(G.degree()).values()))
embeddings

array([ 870, 1418,  851, ...,  845, 1013,  736])

In [197]:
# normalizing degree values
scale = StandardScaler()
embeddings = scale.fit_transform(embeddings.reshape(-1,1))
embeddings

array([[-0.31106038],
       [ 1.87847864],
       [-0.38697505],
       ...,
       [-0.4109481 ],
       [ 0.26029743],
       [-0.8464586 ]])

In [198]:
G.nodes()

NodeView((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 

In [199]:
G.number_of_nodes()

1600

In [200]:
from sklearn.model_selection import train_test_split
import torch_geometric.transforms as T

In [201]:
from torch_geometric.data import InMemoryDataset, Data

In [202]:
# custom dataset
class KarateDataset(InMemoryDataset):
    def __init__(self, transform=None):
        super(KarateDataset, self).__init__('.', transform, None, None)

        data = Data(edge_index=edge_index)
        
        data.num_nodes = G.number_of_nodes()
        
        # embedding 
        data.x = torch.from_numpy(embeddings).type(torch.float32)
        
        # labels
        y = torch.from_numpy(labels).type(torch.long)
        data.y = y.clone().detach()
        
        data.num_classes = 2

        # splitting the data into train, validation and test
        X_train, X_test, y_train, y_test = train_test_split(pd.Series(list(G.nodes())), 
                                                            pd.Series(labels),
                                                            test_size=0.20, 
                                                            random_state=42)
        
        n_nodes = G.number_of_nodes()
        
        # create train and test masks for data
        train_mask = torch.zeros(n_nodes, dtype=torch.bool)
        test_mask = torch.zeros(n_nodes, dtype=torch.bool)
        train_mask[X_train.index] = True
        test_mask[X_test.index] = True
        data['train_mask'] = train_mask
        data['test_mask'] = test_mask

        self.data, self.slices = self.collate([data])

    def _download(self):
        return

    def _process(self):
        return

    def __repr__(self):
        return '{}()'.format(self.__class__.__name__)
    
dataset = KarateDataset()
data = dataset[0]

In [203]:
data['train_mask']

tensor([True, True, True,  ..., True, True, True])

In [204]:
data['test_mask']

tensor([False, False, False,  ..., False, False, False])

In [205]:
dataset[0]

Data(edge_index=[2, 1516564], num_nodes=1600, x=[1600, 1], y=[1600], num_classes=2, train_mask=[1600], test_mask=[1600])

In [206]:
KarateDataset()

KarateDataset()

In [207]:
data

Data(edge_index=[2, 1516564], num_nodes=1600, x=[1600, 1], y=[1600], num_classes=2, train_mask=[1600], test_mask=[1600])

In [208]:
data.num_features

1

In [209]:
data.num_classes

2

In [210]:
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

# GCN model with 2 layers 
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = GCNConv(data.num_features, 32)
        self.conv2 = GCNConv(32, int(data.num_classes))

    def forward(self):
        x, edge_index = data.x, data.edge_index
        x = F.relu(self.conv1(x, edge_index))
        x = F.dropout(x, training=self.training)
        x = self.conv2(x, edge_index)
        return F.log_softmax(x, dim=1)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

data =  data.to(device)

model = Net().to(device) 

In [211]:
torch.manual_seed(42)

optimizer_name = "Adam"
lr = 1e-1
optimizer = getattr(torch.optim, optimizer_name)(model.parameters(), lr=lr)
epochs = 200

def train():
  model.train()
  optimizer.zero_grad()
  F.nll_loss(model()[data.train_mask], data.y[data.train_mask]).backward()
  optimizer.step()

@torch.no_grad()
def test():
  model.eval()
  logits = model()
  mask1 = data['train_mask']
  pred1 = logits[mask1].max(1)[1]
  acc1 = pred1.eq(data.y[mask1]).sum().item() / mask1.sum().item()
  mask = data['test_mask']
  pred = logits[mask].max(1)[1]
  acc = pred.eq(data.y[mask]).sum().item() / mask.sum().item()
  return acc1,acc

for epoch in range(1, epochs):
  train()

train_acc,test_acc = test()

print('#' * 80)
print('Train Accuracy: %s' %train_acc )
print('Test Accuracy: %s' % test_acc)
print('#' * 80)

################################################################################
Train Accuracy: 0.609375
Test Accuracy: 0.60625
################################################################################
